
void print_perms(mode_t st) ;
void clck(int t,int d);
void ls_l(int flag);
void ls(int flag);
void clrspaces(char *temp,int n);
void pwd();
void cd(char* arg[], char base[]);
void echo(char* arg[]);
int exec(char * arg[],int n);
void handler();
void background_check();
int pinfo(char* arg[], char base[]);
int shell_loop();
void remindme(char* arg[]);
void relative_path(char  base[], char pwd[]);
void detect_alarm(int sig);
void check_redirection(char* arg[]);
void redirection(char* arg[],int n);
void jobs();
void kjobs(char* arg[],int number_arguments);
void fg(char* arg[],int n);
void overkill();
void chandler(int signum);
void push(int sig);
void execute_with_pipes(char* arg[],int n);
int checkpipes(char * arg[],int p);
void bg(char* arg[], int n);
int back_size ;
int back_order[4000];
int ppid;
char back_process[400000+1][300];
char message[1024];
int in;
int out;
int flagz;
int flagc;